# Generated by Django 4.0.6 on 2022-07-11 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_id', models.IntegerField(primary_key=1, serialize=False)),
                ('Category_Name', models.CharField(max_length=60)),
                ('Category_Description', models.CharField(max_length=200)),
                ('Category_Image', models.ImageField(upload_to='')),
                ('Category_Status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Package_Itinerary_items',
            fields=[
                ('Itinerary_items_id', models.IntegerField(primary_key=1, serialize=False)),
                ('Itinerary_items_title', models.CharField(max_length=60)),
                ('Itinerary_items_Day', models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=1)),
                ('Itinerary_items_Image', models.ImageField(upload_to='')),
                ('Itinerary_items_Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PackagesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PackagesType_Name', models.CharField(max_length=60)),
                ('PackagesType_Description', models.CharField(max_length=200)),
                ('PackagesType_Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('State_id', models.IntegerField(primary_key=1, serialize=False)),
                ('State_Name', models.CharField(max_length=60)),
                ('State_Description', models.CharField(max_length=200)),
                ('State_Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('Zone_id', models.IntegerField(primary_key=1, serialize=False)),
                ('Zone_Name', models.CharField(max_length=60)),
                ('Zone_Description', models.CharField(max_length=200)),
                ('Zone_Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('Package_id', models.IntegerField(primary_key=1, serialize=False)),
                ('Package_Name', models.CharField(max_length=60)),
                ('Package_Description', models.CharField(max_length=200)),
                ('Package_BannerImage', models.ImageField(upload_to='')),
                ('package_Duration', models.TimeField()),
                ('package_Inclusion', models.CharField(max_length=300)),
                ('package_Category_id', models.IntegerField()),
                ('Category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.category')),
                ('State_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.state')),
                ('Zone_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.zone')),
            ],
        ),
    ]
